### ISSUE TITLE
Missing Docs Required by OSC Governance

### ISSUE THREAD

**Issue by Ranchhand87** [IntersectMBO/cardano-base#482]
The following Required docs are missing and should show on the Main page of Code: CODEOWNERS, CHANGELOG.md

If there are CHANGELOG's please create a top level file and link accordingly. 

The following documents/features are suggested by OSC Governance: Issue Template, PR Template, SECURITY.md

For Reference: https://intersect.gitbook.io/open-source-committee/policies/governance
Also see Documentation and Legal

**Comment by Ranchhand87** [comment]
Please provide an update.

**Comment by lehins** [comment]
@Ranchhand87 PR #497 adds `SECURITY.md`, PR template and `CODEOWNERS`.
Could you please review that PR.

Top level `CHANGELOG.md` file makes no sense for that repo, since each individual package has its own `CHANGELOG.md`. It is important to understand that repository does not get releases, it is individual packages that get released.

Issue template is not needed for this repo. It is ok to submit a free form ticket. Bug reports or feature requests are extremely rare into this repo, so we don't need to have a template for Issues. At least not yet, maybe in the future things will change.
